#!/usr/bin/env ruby

require_relative './lib/rrssw.rb'
require_relative './lib/option.rb'
require_relative './lib/history.rb'
require_relative './lib/logger.rb'
require_relative './lib/config.rb'
require_relative './lib/notification/notification.rb'

options = Option.parse(ARGV)

Slogger.instance.file = options.log if options.log
Slogger.instance.debug_level = options.debug
Slogger.instance.verbose = options.verbose

history = History.new options.database
if options.history
  history.print
  exit
end

config = Config.new options.config

Notification.configure config.notification

Rrssw.new(config.groups, history, options).start
